public_gsheets_url ="https://docs.google.com/spreadsheets/d/1xz8bJUd1T7RddwpONaiH8BYZ6eYPvDxXkrqrctjR4mI/edit?usp=sharing"

DB_USERNAME = "sourja99"
DB_TOKEN = "abcdef"

[some_section]
some_key = 1234